[versions]
agp = "9.3.2"
activity = "1.13.0"
appcompat = "1.8.0"
fragment = "1.9.0"
preference = "1.2.1"
material = "1.14.0"
#noinspection NewerVersionAvailable
aboutLibraries = "14.2.1"
markdown = "4.6.2"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
aboutlibraries-view = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutLibraries" }
markdown-core = { module = "io.noties.markwon:core", version.ref = "markdown" }
markdown-linkify = { module = "io.noties.markwon:linkify", version.ref = "markdown" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }